apiVersion: app.device-operator.io/v1
kind: DeviceDeployment
metadata:
  name: device-vtr
spec:
  startDeviceID: 1
  endDeviceID: 30
  deviceCount: 5
  messagesFrequency: 1
  deploymentTemplate:
    selector:
      matchLabels:
        device: device-vtr
    template:
      spec:
        containers:
        - name: device-job
          image: docker.io/library/device-job:626daf4
        restartPolicy: Always
