apiVersion: app.device-operator.io/v1
kind: DeviceDeployment
metadata:
  name: device-simu-vtr
spec:
  startDeviceID: 1
  endDeviceID: 3
  deviceCount: 1
  messagesFrequency: 1
  deploymentTemplate:
    selector:
      matchLabels:
        device: device-simu-vtr
    template:
      spec:
        containers:
        - name: device-job
          image: docker.io/library/device-job:626daf4
        restartPolicy: Always
